### ISSUE TITLE
Reason for this V2?

### ISSUE THREAD

**Issue by fmalk** [hbsardhara09/node-rake-v2#1]
Let me start by saying I don't have anything against a new version of a probably unmaintained 5 year project, but what does this version specifically addresss or enhance over the original? There's nothing on README and at first glance I noticed a reorganization of some classes and methods, but I'd have to go really deep to understand what benefits does this brings. Does it help over a known bug, like https://github.com/waseem18/node-rake/issues/24 ?

I suggest you make that pretty clear at the start of README.

**Comment by hbsardhara09** [comment]
> Let me start by saying I don't have anything against a new version of a probably unmaintained 5 year project, but what does this version specifically addresss or enhance over the original? There's nothing on README and at first glance I noticed a reorganization of some classes and methods, but I'd have to go really deep to understand what benefits does this brings. Does it help over a known bug, like [waseem18/node-rake#24](https://github.com/waseem18/node-rake/issues/24) ?
> 
> I suggest you make that pretty clear at the start of README.

The old version was not maintained and I found that some code fixes and improvements needed so I have created this new version.
Thanks for suggesting to add that changes details in the starting of the README. Now, I had done that.

**Comment by fmalk** [comment]
Well done! Thanks
